### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'reshape'

### ISSUE THREAD

**Issue by Zumbalamambo** [DavideA/deeplabv2-keras#2]
Im getting the following error,

```
Traceback (most recent call last):
  File "/Users/Downloads/deeplabv2-keras-master/predict.py", line 44, in <module>
    model = DeeplabV2(input_shape=(3, 512, 512), apply_softmax=False)
  File "/Users/Downloads/deeplabv2-keras-master/deeplabV2.py", line 187, in DeeplabV2
    logits = BilinearUpsampling(upsampling=upsampling)(s)
  File "/Users/anaconda/envs/cnn/lib/python3.6/site-packages/keras/engine/topology.py", line 602, in __call__
    output = self.call(inputs, **kwargs)
  File "/Users/Downloads/deeplabv2-keras-master/deeplabV2.py", line 49, in call
    batch_size=2, num_input_channels=self.channels)
  File "/Users/anaconda/envs/cnn/lib/python3.6/site-packages/theano/tensor/nnet/abstract_conv.py", line 1281, in bilinear_upsampling
    up_input = input.reshape((-1, 1, row, col))
AttributeError: 'Tensor' object has no attribute 'reshape'

```

**Comment by DavideA** [comment]
That's weird. Could that depend on the Theano version?

Please try this [reshape interface](http://deeplearning.net/software/theano/library/tensor/basic.html?highlight=reshape#theano.tensor.reshape), something like:
`
import theano.tensor as T
up_input = T.reshape(input, newshape=(-1, 1, row, col))
`

**Comment by Zumbalamambo** [comment]
may I know which version of theano you are using?

**Comment by Zumbalamambo** [comment]
and where should I include the code that you have quoted?

**Comment by DavideA** [comment]
I checked.
If I type theano.\_\_version__ i get
> 0.10.0beta3+118.gaeb6e3c

Have you tried to install the [bleeding edge version](http://deeplearning.net/software/theano/updating.html)?

**Comment by miracle77** [comment]
You should use tf.reshape() instead of tensor.reshape()

**Comment by DavideA** [comment]
Closing.
